import type { ShowcaseMedia } from './showcaseMedia';

export const generatedShowcaseMedia: Record<string, ShowcaseMedia[]> = {
  "brother-cart": [
    { type: "image", src: "/labeled-media/20220322_172518.jpg", alt: "The Arduino Mega test rig wired directly to the cartridge memory bus.", caption: "The Arduino Mega test rig wired directly to the cartridge memory bus." },
    { type: "image", src: "/labeled-media/img_20220904_205323758.jpg", alt: "The replacement cartridge running custom Kirby artwork on the original embroidery machine.", caption: "The replacement cartridge running custom Kirby artwork on the original embroidery machine." },
    { type: "image", src: "/labeled-media/img_20220904_205342009.jpg", alt: "The finished Kirby embroidery produced from the reverse-engineered cartridge format.", caption: "The finished Kirby embroidery produced from the reverse-engineered cartridge format." },
  ],
  "epaper-frame": [
    { type: "image", src: "/labeled-media/img_20240103_231144818.jpg", alt: "The rear of the e-paper frame, showing the compact hand-built enclosure.", caption: "The rear of the e-paper frame, showing the compact hand-built enclosure." },
    { type: "image", src: "/labeled-media/img_20240104_115253224.jpg", alt: "The frame's rear assembly and concealed display electronics.", caption: "The frame's rear assembly and concealed display electronics." },
  ],
  "flare-on": [
    { type: "image", src: "/labeled-media/img_20231127_190526180.jpg", alt: "The ninth annual Flare-On medal, awarded for completing the full challenge set.", caption: "The ninth annual Flare-On medal, awarded for completing the full challenge set." },
    { type: "image", src: "/labeled-media/img_20240710_173842766.jpg", alt: "The 2023 finisher pennant, marking another completed Flare-On challenge.", caption: "The 2023 finisher pennant, marking another completed Flare-On challenge." },
    { type: "image", src: "/labeled-media/img_20250205_194546494.jpg", alt: "The 2024 Flare-On medal, earned by completing the challenge for a fourth year.", caption: "The 2024 Flare-On medal, earned by completing the challenge for a fourth year." },
  ],
  "jrb8": [
    { type: "image", src: "/labeled-media/img_20260708_141450040.jpg", alt: "The manufactured JRB8 on its Tiny Tapeout carrier, with external QSPI program storage.", caption: "The manufactured JRB8 on its Tiny Tapeout carrier, with external QSPI program storage." },
    { type: "image", src: "/labeled-media/img_20260710_230016453.jpg", alt: "A Tang Nano 9K FPGA used to validate the Verilog design before fabrication.", caption: "A Tang Nano 9K FPGA used to validate the Verilog design before fabrication." },
    { type: "video", src: "/labeled-media/vid_20250204_230808166.mp4", caption: "An early bench test of the fabricated CPU driving its LED program display." },
    { type: "video", src: "/labeled-media/vid_20250205_113352383.mp4", caption: "A stable bench test of the original 8-bit computer running its display program." },
    { type: "video", src: "/labeled-media/vid_20260712_003752420.mp4", caption: "The fabricated JRB8 running a compiled spinning-cube demonstration." },
    { type: "video", src: "/labeled-media/vid_20260712_025501152.mp4", caption: "A slower spinning-cube build with the JRB8 identity rendered on screen." },
  ],
  "led-display": [
    { type: "image", src: "/labeled-media/20211225_234441.jpg", alt: "The first low-resolution prototype exposed severe light bleed between pixels.", caption: "The first low-resolution prototype exposed severe light bleed between pixels." },
    { type: "image", src: "/labeled-media/20230122_192240.jpg", alt: "The ESP32 HUB75 driver schematic behind the display controller.", caption: "The ESP32 HUB75 driver schematic behind the display controller." },
    { type: "image", src: "/labeled-media/img_20230129_213119097.jpg", alt: "The next revision running the clock with a full-colour spectrum treatment.", caption: "The next revision running the clock with a full-colour spectrum treatment." },
    { type: "image", src: "/labeled-media/img_20230130_160102525.jpg", alt: "The compact controller wiring tucked behind the HUB75 panel.", caption: "The compact controller wiring tucked behind the HUB75 panel." },
    { type: "image", src: "/labeled-media/img_20260408_112333152.jpg", alt: "The display running a Frieren animation beneath the moon lamp.", caption: "The display running a Frieren animation beneath the moon lamp." },
    { type: "video", src: "/labeled-media/vid_20230129_213119905.mp4", caption: "An early clock revision testing a smoothly shifting rainbow palette." },
    { type: "video", src: "/labeled-media/vid_20230130_151111512.mp4", caption: "A spectrum animation running on the revised display hardware." },
    { type: "video", src: "/labeled-media/vid_20230130_151518415.mp4", caption: "The spectrum renderer sweeping colour across the full panel." },
    { type: "video", src: "/labeled-media/vid_20240902_210527607.mp4", caption: "A later build revisiting the animated rainbow clock face." },
    { type: "video", src: "/labeled-media/vid_20250612_013910584.mp4", caption: "The current web interface controlling modes and animations in real time." },
  ],
  "light-gun": [
    { type: "image", src: "/labeled-media/img_20250816_005809066.jpg", alt: "The open light-gun enclosure during wiring and final assembly.", caption: "The open light-gun enclosure during wiring and final assembly." },
    { type: "image", src: "/labeled-media/img_20250816_005832203.jpg", alt: "The foot pedal and its compact battery enclosure during assembly.", caption: "The foot pedal and its compact battery enclosure during assembly." },
    { type: "image", src: "/labeled-media/img_20250816_005950219.jpg", alt: "The completed internal layout, including display, controls, and wireless electronics.", caption: "The completed internal layout, including display, controls, and wireless electronics." },
    { type: "image", src: "/labeled-media/img_20250820_163442058.jpg", alt: "The finished wireless light gun in its printed enclosure.", caption: "The finished wireless light gun in its printed enclosure." },
    { type: "image", src: "/labeled-media/img_20250820_163454397.jpg", alt: "The rear display provides calibration and on-device feedback.", caption: "The rear display provides calibration and on-device feedback." },
    { type: "image", src: "/labeled-media/img_20250820_163458670.jpg", alt: "The opposite side of the completed enclosure and control layout.", caption: "The opposite side of the completed enclosure and control layout." },
    { type: "image", src: "/labeled-media/img_20250825_015203622.jpg", alt: "The finished foot pedal used for cover and auxiliary input.", caption: "The finished foot pedal used for cover and auxiliary input." },
    { type: "video", src: "/labeled-media/p1660999.mp4", caption: "The wireless light gun running Time Crisis with working recoil feedback." },
  ],
  "moon-lamp": [
    { type: "image", src: "/labeled-media/img_20250604_232326646.jpg", alt: "The moon lamp paired with an earlier revision of the LED clock.", caption: "The moon lamp paired with an earlier revision of the LED clock." },
    { type: "image", src: "/labeled-media/img_20250604_232341029.jpg", alt: "The exposed lamp mechanism with the printed globe removed.", caption: "The exposed lamp mechanism with the printed globe removed." },
    { type: "image", src: "/labeled-media/img_20250612_182448668.jpg", alt: "The illuminated moon globe on its motorised printed stand.", caption: "The illuminated moon globe on its motorised printed stand." },
    { type: "image", src: "/labeled-media/img_20250622_235133126.jpg", alt: "The completed moon lamp lit against a clear background.", caption: "The completed moon lamp lit against a clear background." },
    { type: "image", src: "/labeled-media/img_20260708_141050081.jpg", alt: "The revised moon shell taking shape during a continuous 3D print.", caption: "The revised moon shell taking shape during a continuous 3D print." },
    { type: "image", src: "/labeled-media/img_20260708_141144067.jpg", alt: "The first lamp revision with its globe removed, exposing the motor and mount.", caption: "The first lamp revision with its globe removed, exposing the motor and mount." },
    { type: "video", src: "/labeled-media/vid_20250622_232319227.mp4", caption: "The illuminated globe rotating on the finished stand." },
    { type: "video", src: "/labeled-media/vid_20260708_141009787.mp4", caption: "The revised moon shell being produced on the 3D printer." },
  ],
  "motor-controller": [
    { type: "image", src: "/labeled-media/img_20260325_005025569.jpg", alt: "The controller clamped to the bench for motor and robot-leg testing.", caption: "The controller clamped to the bench for motor and robot-leg testing." },
    { type: "image", src: "/labeled-media/img_20260325_005031637.jpg", alt: "The controller mounted behind the motor during closed-loop testing.", caption: "The controller mounted behind the motor during closed-loop testing." },
    { type: "image", src: "/labeled-media/img_20260325_005037843.jpg", alt: "The complete bench setup used to validate the controller against a robot leg.", caption: "The complete bench setup used to validate the controller against a robot leg." },
    { type: "image", src: "/labeled-media/img_20260708_171726261.jpg", alt: "The first controller revision with rework added while isolating power and sensing faults.", caption: "The first controller revision with rework added while isolating power and sensing faults." },
    { type: "image", src: "/labeled-media/img_20260708_172055064.jpg", alt: "A Moteus controller and motor used as a known-good reference assembly.", caption: "A Moteus controller and motor used as a known-good reference assembly." },
    { type: "image", src: "/labeled-media/img_20260708_172104100.jpg", alt: "The reverse of the reference Moteus controller.", caption: "The reverse of the reference Moteus controller." },
    { type: "image", src: "/labeled-media/img_20260708_172213370.jpg", alt: "A separate controller used to verify the motor independently during debugging.", caption: "A separate controller used to verify the motor independently during debugging." },
    { type: "video", src: "/labeled-media/vid_20250905_221318387.mp4", caption: "The first successful motor rotation under control of the custom board." },
  ],
  "nintendo-ds": [
    { type: "image", src: "/labeled-media/img_20250910_104542261.jpg", alt: "The damaged Nintendo DS connector secured for precision hot-air rework.", caption: "The damaged Nintendo DS connector secured for precision hot-air rework." },
    { type: "image", src: "/labeled-media/img_20250910_105543316.jpg", alt: "The failed connector removed cleanly before fitting its replacement.", caption: "The failed connector removed cleanly before fitting its replacement." },
    { type: "video", src: "/labeled-media/vid_20250919_155151386.mp4", caption: "The repaired console passing its display, touch, and audio checks." },
    { type: "video", src: "/labeled-media/vid_20250919_155316304.mp4", caption: "A second functional test confirming the completed Nintendo DS repair." },
  ],
  "robodog": [
    { type: "image", src: "/labeled-media/img_20241111_122352651.jpg", alt: "The first complete leg assembly with motor, joints, and printed structure.", caption: "The first complete leg assembly with motor, joints, and printed structure." },
    { type: "image", src: "/labeled-media/img_20241111_122401748.jpg", alt: "The leg assembly inverted to inspect its joint spacing and belt paths.", caption: "The leg assembly inverted to inspect its joint spacing and belt paths." },
    { type: "image", src: "/labeled-media/img_20241111_122437126.jpg", alt: "A side view of the first articulated leg module.", caption: "A side view of the first articulated leg module." },
    { type: "image", src: "/labeled-media/img_20250505_114508245.jpg", alt: "Two assembled legs during the first half-chassis fit check.", caption: "Two assembled legs during the first half-chassis fit check." },
    { type: "image", src: "/labeled-media/img_20250505_114518195.jpg", alt: "The paired leg modules before their chassis alignment was corrected.", caption: "The paired leg modules before their chassis alignment was corrected." },
    { type: "image", src: "/labeled-media/img_20250712_195157605.jpg", alt: "The aluminium spine and paired leg modules taking shape on the workbench.", caption: "The aluminium spine and paired leg modules taking shape on the workbench." },
    { type: "image", src: "/labeled-media/img_20250712_211802667.jpg", alt: "Assembly work on the central frame and leg mounts.", caption: "Assembly work on the central frame and leg mounts." },
    { type: "image", src: "/labeled-media/img_20250713_014440354.jpg", alt: "One assembled half showing the aluminium spine, paired joints, and controller mounting.", caption: "One assembled half showing the aluminium spine, paired joints, and controller mounting." },
    { type: "image", src: "/labeled-media/img_20250713_014445742.jpg", alt: "The half-chassis from the opposite side, showing the motor and belt layout.", caption: "The half-chassis from the opposite side, showing the motor and belt layout." },
    { type: "image", src: "/labeled-media/img_20250720_021517729.jpg", alt: "All four legs connected for the first full-chassis wiring and fit check.", caption: "All four legs connected for the first full-chassis wiring and fit check." },
    { type: "image", src: "/labeled-media/img_20250721_233253211.jpg", alt: "The first four-legged assembly before the rear geometry was revised.", caption: "The first four-legged assembly before the rear geometry was revised." },
    { type: "image", src: "/labeled-media/img_20260304_014120708.jpg", alt: "A half-chassis test assembly with two articulated legs installed.", caption: "A half-chassis test assembly with two articulated legs installed." },
    { type: "image", src: "/labeled-media/img_20260304_014125093.jpg", alt: "The robot dog undergoing frame and wiring work at the bench.", caption: "The robot dog undergoing frame and wiring work at the bench." },
    { type: "image", src: "/labeled-media/img_20260325_005041598.jpg", alt: "The paired leg assembly used during controller bring-up.", caption: "The paired leg assembly used during controller bring-up." },
    { type: "image", src: "/labeled-media/img_20260325_005055913.jpg", alt: "A single articulated leg prepared for motor-control testing.", caption: "A single articulated leg prepared for motor-control testing." },
    { type: "image", src: "/labeled-media/img_20260417_221157940.jpg", alt: "The full quadruped assembled on the revised aluminium frame.", caption: "The full quadruped assembled on the revised aluminium frame." },
    { type: "image", src: "/labeled-media/img_20260524_220322875.jpg", alt: "The nearly complete quadruped during final bench integration.", caption: "The nearly complete quadruped during final bench integration." },
    { type: "image", src: "/labeled-media/img_20260708_141350321.jpg", alt: "The nearly complete quadruped showing final leg spacing and the full aluminium frame.", caption: "The nearly complete quadruped showing final leg spacing and the full aluminium frame." },
    { type: "image", src: "/labeled-media/img_20260708_141406457.jpg", alt: "The completed underside with all four legs, controllers, and wiring visible.", caption: "The completed underside with all four legs, controllers, and wiring visible." },
    { type: "image", src: "/labeled-media/img_20260708_141408312.jpg", alt: "A close view of the rear joints, belt reductions, and power connections.", caption: "A close view of the rear joints, belt reductions, and power connections." },
  ],
  "side-quests": [
    { type: "image", src: "/labeled-media/20211225_233717.jpg", alt: "An internet-connected motor assembly built to automate a set of window blinds.", caption: "An internet-connected motor assembly built to automate a set of window blinds." },
    { type: "image", src: "/labeled-media/20211226_143945.jpg", alt: "A workbench snapshot of the electronics, fabrication tools, and experiments in progress.", caption: "A workbench snapshot of the electronics, fabrication tools, and experiments in progress." },
    { type: "image", src: "/labeled-media/20211226_144000.jpg", alt: "Soldering, crimping, and prototyping tools gathered for a run of small builds.", caption: "Soldering, crimping, and prototyping tools gathered for a run of small builds." },
    { type: "image", src: "/labeled-media/20211226_155530.jpg", alt: "A Raspberry Pi HDMI capture setup driving reactive ambient lighting behind a television.", caption: "A Raspberry Pi HDMI capture setup driving reactive ambient lighting behind a television." },
    { type: "image", src: "/labeled-media/20211226_160458.jpg", alt: "The reactive TV-lighting controller during wiring and soldering.", caption: "The reactive TV-lighting controller during wiring and soldering." },
    { type: "video", src: "/labeled-media/20211226_164852.mp4", caption: "Hyperion matching the surrounding LED strip to the television image in real time." },
    { type: "image", src: "/labeled-media/20230406_0004.jpg", alt: "Infrared photography captured with a camera converted for full-spectrum imaging.", caption: "Infrared photography captured with a camera converted for full-spectrum imaging." },
    { type: "image", src: "/labeled-media/20230406_0008.jpg", alt: "A second infrared study from the full-spectrum camera conversion.", caption: "A second infrared study from the full-spectrum camera conversion." },
    { type: "image", src: "/labeled-media/20230406_0480.jpg", alt: "An alternate infrared filter revealing a different balance of foliage and sky.", caption: "An alternate infrared filter revealing a different balance of foliage and sky." },
    { type: "image", src: "/labeled-media/20230406_0481.jpg", alt: "Full-spectrum camera testing with a second infrared lens and filter combination.", caption: "Full-spectrum camera testing with a second infrared lens and filter combination." },
    { type: "image", src: "/labeled-media/20230406_0482.jpg", alt: "A further infrared composition used to compare converted-camera filters.", caption: "A further infrared composition used to compare converted-camera filters." },
    { type: "image", src: "/labeled-media/img_20230131_214225304.jpg", alt: "The ESP32 schematic for the air-quality clock and sensor interface.", caption: "The ESP32 schematic for the air-quality clock and sensor interface." },
    { type: "image", src: "/labeled-media/img_20260417_221202847.jpg", alt: "The main project bench, tool storage, and active electronics workspace.", caption: "The main project bench, tool storage, and active electronics workspace." },
    { type: "image", src: "/labeled-media/img_20260708_141219876.jpg", alt: "An ESP32 kitchen assistant combining animated clock faces with voice-triggered queries.", caption: "An ESP32 kitchen assistant combining animated clock faces with voice-triggered queries." },
    { type: "image", src: "/labeled-media/img_20260712_140121760.jpg", alt: "The sensor, display, and controller wiring inside the air-quality clock.", caption: "The sensor, display, and controller wiring inside the air-quality clock." },
    { type: "image", src: "/labeled-media/img_20260712_140149943.jpg", alt: "The assembled air-quality clock running on the bench.", caption: "The assembled air-quality clock running on the bench." },
    { type: "video", src: "/labeled-media/vid_20240613_182950394.mp4", caption: "A mechanical segment clock advancing its motor-driven display by one minute." },
    { type: "video", src: "/labeled-media/vid_20260622_202840254.mp4", caption: "The kitchen assistant cycling through its ported Dwitter animations." },
    { type: "video", src: "/labeled-media/vid_20260622_203013682.mp4", caption: "A voice-triggered kitchen query demonstrated on the ESP32 assistant." },
  ],
  "single-key-keyboard": [
    { type: "image", src: "/labeled-media/img_20230829_014051610.jpg", alt: "The controller and key PCBs before they were joined into the finished keyboard.", caption: "The controller and key PCBs before they were joined into the finished keyboard." },
    { type: "image", src: "/labeled-media/img_20230829_014111730.jpg", alt: "The assembled single-key keyboard with its custom round controller board.", caption: "The assembled single-key keyboard with its custom round controller board." },
    { type: "image", src: "/labeled-media/img_20231107_180616106.jpg", alt: "A small production run of single-key keyboards prepared as giveaways.", caption: "A small production run of single-key keyboards prepared as giveaways." },
    { type: "video", src: "/labeled-media/vid_20231019_152026895.mp4", caption: "The single key triggering its programmed multi-character output." },
  ],
  "wallet": [
    { type: "image", src: "/labeled-media/img_20250430_223514652.jpg", alt: "The lever lifting the loaded cards into a staggered, selectable stack.", caption: "The lever lifting the loaded cards into a staggered, selectable stack." },
    { type: "image", src: "/labeled-media/img_20250430_223634873.jpg", alt: "The hinged rear compartment for notes, coins, and other bulky items.", caption: "The hinged rear compartment for notes, coins, and other bulky items." },
    { type: "image", src: "/labeled-media/img_20250430_224321506.jpg", alt: "The finished wallet closed for everyday carry.", caption: "The finished wallet closed for everyday carry." },
    { type: "image", src: "/labeled-media/img_20250430_224614575.jpg", alt: "The raised lever and fully deployed cascade of cards.", caption: "The raised lever and fully deployed cascade of cards." },
    { type: "video", src: "/labeled-media/vid_20240628_014412453.mp4", caption: "The compact wallet demonstrated in everyday use." },
    { type: "video", src: "/labeled-media/vid_20240628_014445998.mp4", caption: "The cascading card lift and rear compartment demonstrated together." },
  ],
};
